#!/usr/bin/env bash
# This script displays all acive IPv4 addresses on the m
interfaces=$(ip -o link show | awk -F': ' '{print $2}')

# Iterate over each interface and retrieve its IPv4 address
for interface in $interfaces; do
    ipv4=$(ip -o -4 addr show dev $interface | awk '{print $4}')
    if [[ -n "$ipv4" ]]; then
        echo "Interface: $interface"
        echo "IPv4 Address: $ipv4"
        echo
    fi
done

